/**
 * UBUMWE AGRI - Base de Donnees Maladies Offline
 * Sources: FAO, IITA, CABI PlantWise, OIE, CGIAR
 */

const SEVERITY_COLOR = {
  'faible':'bg-blue-100 text-blue-800',
  'modere':'bg-amber-100 text-amber-800',
  'grave':'bg-orange-100 text-orange-800',
  'critique':'bg-red-100 text-red-800'
};

const PLANT_DISEASES_DB = [
  {
    "id": "pd-1",
    "plant": "Manioc",
    "plant_rn": "Imyumbati",
    "plant_en": "Cassava",
    "name": "Mosaique du Manioc (CMD)",
    "name_en": "Cassava Mosaic Disease",
    "severity": "grave",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Cassava_mosaic.jpg/320px-Cassava_mosaic.jpg",
    "symptoms": "Feuilles avec taches jaunes en mosaique, deformation, retard de croissance, tubercules petits",
    "symptoms_rn": "Amababi afise amabara umuhondo, yagagaziwe, imyumbati mike",
    "symptoms_en": "Yellow mosaic patches on leaves, deformation, stunted growth, small tubers",
    "cause": "Virus transmis par la mouche blanche (Bemisia tabaci)",
    "diagnosis": "Motif mosaique jaune-vert. Presence de mouches blanches sous les feuilles",
    "treatment": "1. Arracher et bruler les plants infectes\n2. Boutures saines certifiees\n3. Imidaclopride 200g/L contre mouche blanche\n4. Varietes resistantes CMD (TME 419)",
    "treatment_rn": "1. Kurumuna ibimera biranduye\n2. Gukoresha indamutso nziza\n3. Umuti kuri inzuki",
    "treatment_en": "1. Remove and burn infected plants\n2. Certified cuttings\n3. Imidacloprid 200g/L\n4. Resistant varieties TME 419",
    "prevention": "Inspecter les boutures. Rotation des cultures. Eviter champs proches de plants infectes",
    "source": "FAO/IITA"
  },
  {
    "id": "pd-2",
    "plant": "Manioc",
    "plant_rn": "Imyumbati",
    "plant_en": "Cassava",
    "name": "Bacteriose du Manioc",
    "name_en": "Cassava Bacterial Blight",
    "severity": "grave",
    "image": "https://www.iita.org/wp-content/uploads/2016/03/cassava-bacterial-blight.jpg",
    "symptoms": "Taches angulaires brun-noir sur feuilles, exsudat gommeux sur tiges, fletrissement",
    "symptoms_en": "Angular brown-black spots on leaves, gummy stem exudate, wilting",
    "cause": "Bacterie Xanthomonas axonopodis, favorisee par la pluie",
    "diagnosis": "Taches foliaires angulaires avec halo jaune. Exsudat blanc cremeux",
    "treatment": "1. Supprimer parties infectees\n2. Eau de Javel 10% sur outils\n3. Bouillie Bordelaise 1%\n4. Varietes tolerantes",
    "treatment_en": "1. Remove infected parts\n2. 10% bleach on tools\n3. Bordeaux mixture 1%",
    "prevention": "Eviter blessures mecaniques. Ne pas planter en saison des pluies intenses",
    "source": "IITA/CABI"
  },
  {
    "id": "pd-3",
    "plant": "Mais",
    "plant_rn": "Ibigori",
    "plant_en": "Corn",
    "name": "Chenille Legionnaire d'Automne",
    "name_en": "Fall Armyworm",
    "severity": "critique",
    "image": "./img-mais-maladie.jpg.jpg",
    "symptoms": "Trous irreguliers dans les feuilles, sciure sur feuilles, chenilles vertes dans cornet",
    "symptoms_rn": "Imyoyo mu mababi, ivumbi, ibibabi bibora",
    "symptoms_en": "Irregular holes in leaves, sawdust frass, striped green caterpillars in funnel",
    "cause": "Insecte Spodoptera frugiperda - papillon migrateur",
    "diagnosis": "Chenilles avec Y inverse blanc sur la tete. Degats en entonnoir",
    "treatment": "1. Intervention precoce V3-V6\n2. Chlorpyrifos 48% EC\n3. Emamectin Benzoate\n4. Beauveria bassiana (bio)\n5. Pyrethrine vegetale",
    "treatment_rn": "1. Gukora vuba\n2. Umuti Chlorpyrifos\n3. Umuti wa kamere Pyrethrine",
    "treatment_en": "1. Early intervention V3-V6\n2. Chlorpyrifos 48% EC\n3. Emamectin Benzoate\n4. Beauveria bassiana",
    "prevention": "Surveillance hebdomadaire. Pieges a pheromones. Favoriser predateurs naturels",
    "source": "FAO 2022/CABI"
  },
  {
    "id": "pd-4",
    "plant": "Mais",
    "plant_rn": "Ibigori",
    "plant_en": "Corn",
    "name": "Rouille du Mais",
    "name_en": "Maize Rust",
    "severity": "modere",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Corn_rust_close.jpg/320px-Corn_rust_close.jpg",
    "symptoms": "Pustules orange-brun sur les deux faces des feuilles, poudre orange, jaunissement precoce",
    "symptoms_en": "Orange-brown pustules on both leaf surfaces, orange powder, early yellowing",
    "cause": "Champignon Puccinia sorghi, favorise par humidite",
    "diagnosis": "Pustules sporales ovales brun-rouge. Poudre orange au toucher",
    "treatment": "1. Mancozebe 80% WP (2.5 kg/ha)\n2. Tebuconazole 250 EC\n3. Traitement preventif debut saison des pluies",
    "treatment_en": "1. Mancozeb 80% WP\n2. Tebuconazole 250 EC\n3. Preventive treatment",
    "prevention": "Varietes resistantes. Rotation cultures. Eviter irrigation foliaire",
    "source": "CIMMYT"
  },
  {
    "id": "pd-5",
    "plant": "Haricot",
    "plant_rn": "Ibiharage",
    "plant_en": "Bean",
    "name": "Anthracnose du Haricot",
    "name_en": "Bean Anthracnose",
    "severity": "grave",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Colletotrichum_bean.jpg/320px-Colletotrichum_bean.jpg",
    "symptoms": "Taches brun-noires sur cosses et tiges, lesions rouges sur feuilles, grains taches noirs",
    "symptoms_en": "Dark brown-black spots on pods and stems, red lesions on leaves, black-stained grains",
    "cause": "Champignon Colletotrichum lindemuthianum, favorise par pluie",
    "diagnosis": "Lesions sur cosses avec centre rose saumon et bord brun-rouge",
    "treatment": "1. Thirame 80% WP sur semences (3g/kg)\n2. Mancozebe + Metalaxyl foliaire\n3. Detruire residus de culture\n4. Rotation 3 ans",
    "treatment_en": "1. Thiram 80% WP seed treatment\n2. Mancozeb + Metalaxyl foliar\n3. Destroy crop residues",
    "prevention": "Semences certifiees. Eviter travail en sol mouille",
    "source": "CIAT/FAO"
  },
  {
    "id": "pd-6",
    "plant": "Cafetier",
    "plant_rn": "Ikawa",
    "plant_en": "Coffee",
    "name": "Rouille Orangee du Cafe",
    "name_en": "Coffee Leaf Rust",
    "severity": "critique",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Coffee_leaf_rust.jpg/320px-Coffee_leaf_rust.jpg",
    "symptoms": "Poudre orangee sous les feuilles, taches jaunes dessus, chute des feuilles, perte de production",
    "symptoms_rn": "Ifu ya orange munsi amababi, amababi agwa, rusarenda igabanuka",
    "symptoms_en": "Orange powder under leaves, yellow spots on top, leaf drop, major yield loss",
    "cause": "Champignon Hemileia vastatrix, sporulation lors de pluies",
    "diagnosis": "Spores oranges en croissant face inferieure. Defoliation progressive",
    "treatment": "1. Bouillie Bordelaise 1% (cuivre)\n2. Oxychlorure de cuivre 50% WP\n3. Minimum 3-4 traitements par an\n4. Appliquer avant saison des pluies",
    "treatment_en": "1. Bordeaux mixture 1%\n2. Copper oxychloride 50% WP\n3. Minimum 3-4 treatments per year",
    "prevention": "Taille aerante. Ombrage modere. Varietes resistantes (Ruiru 11)",
    "source": "ICO/FAO"
  },
  {
    "id": "pd-7",
    "plant": "Banane",
    "plant_rn": "Ibitoke",
    "plant_en": "Banana",
    "name": "Fusariose Panama TR4",
    "name_en": "Fusarium Wilt Panama TR4",
    "severity": "critique",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Banana_Panama_disease.jpg/320px-Banana_Panama_disease.jpg",
    "symptoms": "Jaunissement et fletrissement de bas en haut, brunissement vasculaire a la coupe, mort de la plante",
    "symptoms_en": "Yellowing and wilting bottom to top, vascular browning at cut, plant death",
    "cause": "Champignon Fusarium oxysporum TR4 dans le sol",
    "diagnosis": "Coupe pseudo-tronc: brunissement vasculaire rouge-brun caracteristique",
    "treatment": "1. PAS DE TRAITEMENT CURATIF\n2. Arracher et bruler immediatement\n3. Eau de Javel sur outils\n4. Replanter varietes resistantes FHIA-17",
    "treatment_en": "1. NO CURATIVE TREATMENT\n2. Remove and burn immediately\n3. Bleach on tools\n4. Replant resistant FHIA-17",
    "prevention": "Quarantaine stricte. Rejets certifies uniquement. Ne jamais deplacer sol infecte",
    "source": "FAO/Bioversity"
  },
  {
    "id": "pd-8",
    "plant": "Pomme de terre",
    "plant_rn": "Ibirayi",
    "plant_en": "Potato",
    "name": "Mildiou de la Pomme de Terre",
    "name_en": "Late Blight",
    "severity": "critique",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Potato_late_blight.jpg/320px-Potato_late_blight.jpg",
    "symptoms": "Taches brun-noir sur feuilles avec duvet blanc dessous, tiges noires pourrissantes, tubercules pourris",
    "symptoms_rn": "Amababi afise amabara umukara, imizi iboze, ibirayi biboze",
    "symptoms_en": "Brown-black spots on leaves with white down underneath, black rotting stems, rotten tubers",
    "cause": "Oomycete Phytophthora infestans, conditions fraiches et humides",
    "diagnosis": "Taches necrotiques irregulieres, moisissure blanche sous feuilles par temps humide",
    "treatment": "1. Mancozebe 2.5 kg/ha tous les 7 jours\n2. Metalaxyl-M + Mancozebe\n3. Cymoxanil + Mancozebe\n4. Arreter irrigation foliaire",
    "treatment_en": "1. Mancozeb 2.5 kg/ha every 7 days\n2. Metalaxyl-M + Mancozeb\n3. Cymoxanil + Mancozeb",
    "prevention": "Varietes resistantes. Tubercules semences certifies. Eviter irrigation par aspersion",
    "source": "CIP/FAO"
  },
  {
    "id": "pd-9",
    "plant": "Riz",
    "plant_rn": "Umuceri",
    "plant_en": "Rice",
    "name": "Pyriculariose du Riz",
    "name_en": "Rice Blast",
    "severity": "grave",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Rice_blast_disease.jpg/320px-Rice_blast_disease.jpg",
    "symptoms": "Taches en losange gris-brun sur feuilles, noeuds noircissent et cassent, grains vides",
    "symptoms_en": "Diamond-shaped grey-brown spots on leaves, nodes blacken and break, empty grains",
    "cause": "Champignon Pyricularia oryzae",
    "diagnosis": "Lesions rhombiques caracteristiques. Noeuds noircis. Analyse microscopique confirme",
    "treatment": "1. Tricyclazole 75% WP (600 g/ha)\n2. Isoprothiolane\n3. Appliquer au tallage et emergence paniculaire\n4. Reduire azote excessif",
    "treatment_en": "1. Tricyclazole 75% WP\n2. Isoprothiolane\n3. Apply at tillering and panicle emergence",
    "prevention": "Varietes resistantes. Semences certifiees. Eviter exces azote",
    "source": "IRRI/FAO"
  },
  {
    "id": "pd-10",
    "plant": "Sorgho",
    "plant_rn": "Amasaka",
    "plant_en": "Sorghum",
    "name": "Charbon du Sorgho",
    "name_en": "Sorghum Head Smut",
    "severity": "grave",
    "image": "https://www.plantwise.org/assets/images/pest-placeholder.jpg",
    "symptoms": "Epis remplaces de masses poudreuses noires, odeur caracteristique, grains absents",
    "symptoms_en": "Ears replaced by black powdery masses, characteristic smell, absent grains",
    "cause": "Champignon Sporisorium reilianum dans le sol",
    "diagnosis": "Masses poudreuses noires a la place des grains",
    "treatment": "1. Traitement semences Carbendazime\n2. Rotation cultures 2-3 ans\n3. Detruire plantes infectees avant sporulation",
    "treatment_en": "1. Seed treatment Carbendazim\n2. 2-3 year rotation\n3. Destroy plants before sporulation",
    "prevention": "Semences certifiees. Rotation cultures",
    "source": "ICRISAT/FAO"
  }
];

const ANIMAL_DISEASES_DB = [
  {
    "id": "ad-1",
    "animal": "Vache",
    "animal_rn": "Inka",
    "animal_en": "Cow",
    "name": "Fievre Aphteuse",
    "name_en": "Foot and Mouth Disease",
    "severity": "critique",
    "is_zoonotic": true,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/FMD_in_cattle.jpg/320px-FMD_in_cattle.jpg",
    "symptoms": "Fievre brutale 40-41C, vesicules sur langue, pieds et pis, boiterie severe, salive abondante",
    "symptoms_rn": "Ubushuhe 40-41C, amahinda ku rurimi no ku bikiriro, ntashobora gutunga neza",
    "symptoms_en": "Sudden fever 40-41C, blisters on tongue, feet and udder, severe lameness, excessive salivation",
    "cause": "Virus - contagion foudroyante entre troupeaux",
    "diagnosis": "Vesicules sur muqueuses et pieds. Test PCR confirmatoire",
    "treatment": "1. Isolement immediat\n2. Antiseptiques sur lesions\n3. Anti-inflammatoires (Flunixine)\n4. Antibiotiques si surinfection\n5. Soutien nutritionnel",
    "treatment_en": "1. Immediate isolation\n2. Antiseptics on lesions\n3. Anti-inflammatories\n4. Antibiotics if superinfection",
    "prevention": "Vaccination bivalente annuelle obligatoire. Controle mouvements animaux",
    "vaccine": "Vaccin bivalent FMD (souches O et A) - 2 fois par an minimum",
    "source": "OIE/FAO"
  },
  {
    "id": "ad-2",
    "animal": "Vache",
    "animal_rn": "Inka",
    "animal_en": "Cow",
    "name": "Theileriose (Fievre de la Cote Est)",
    "name_en": "East Coast Fever",
    "severity": "critique",
    "is_zoonotic": false,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/East_coast_fever.jpg/320px-East_coast_fever.jpg",
    "symptoms": "Fievre 40-41C persistante, gonflement ganglions parotidiens, difficultes respiratoires, larmoiement, amaigrissement rapide",
    "symptoms_en": "Persistent fever 40-41C, swollen parotid lymph nodes, breathing difficulties, tearing, rapid weight loss",
    "cause": "Parasite Theileria parva transmis par tiques Rhipicephalus appendiculatus",
    "diagnosis": "Gonflement ganglion parotidien. Frottis sanguin: schizontes dans lymphocytes. Tres frequent au Burundi",
    "treatment": "1. Buparvaquone (Butalex) 2.5 mg/kg IM\n2. Fluidotherapie\n3. Antipyretiques\n4. Vitamines B\n5. Traitement precoce crucial",
    "treatment_en": "1. Buparvaquone (Butalex) 2.5 mg/kg IM\n2. Fluid therapy\n3. Antipyretics\n4. B vitamins",
    "prevention": "Lutte contre tiques par bains acaricides reguliers. Vaccination ECF possible",
    "vaccine": "ECF immunisation (infection-and-treatment method)",
    "source": "FAO/ILRAD"
  },
  {
    "id": "ad-3",
    "animal": "Vache",
    "animal_rn": "Inka",
    "animal_en": "Cow",
    "name": "Brucellose Bovine",
    "name_en": "Bovine Brucellosis",
    "severity": "grave",
    "is_zoonotic": true,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Brucellosis_cow.jpg/320px-Brucellosis_cow.jpg",
    "symptoms": "Avortements dernier tiers gestation, retention placentaire, infertilite, orchite chez le male",
    "symptoms_en": "Abortions in last trimester, retained placenta, infertility, orchitis in males",
    "cause": "Bacterie Brucella abortus - zoonose grave (danger pour l'homme)",
    "diagnosis": "Test RBPT ou Wright positif. Avortement caracteristique. DANGER: ne pas toucher placenta sans gants",
    "treatment": "1. Abattre les positifs (politique sanitaire)\n2. Traitement de soutien post-avortement\n3. Antibiotiques peu efficaces",
    "treatment_en": "1. Cull positive animals\n2. Post-abortion supportive treatment",
    "prevention": "Vaccination velles 3-8 mois. Test et abattage des positifs. Hygiene a la mise-bas. Porter gants",
    "vaccine": "Vaccin RB51 ou S19 pour velles 3-8 mois",
    "source": "OIE/FAO"
  },
  {
    "id": "ad-4",
    "animal": "Chevre",
    "animal_rn": "Impene",
    "animal_en": "Goat",
    "name": "Peste des Petits Ruminants (PPR)",
    "name_en": "Peste des Petits Ruminants",
    "severity": "critique",
    "is_zoonotic": false,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/PPR_goat.jpg/320px-PPR_goat.jpg",
    "symptoms": "Fievre 41-42C, ecoulements nez et yeux abondants, erosions buccales, pneumonie, diarrhee severe, mortalite jusqu'a 90%",
    "symptoms_rn": "Ubushuhe bukabije, amazuru, indwara z'amahaha, impene zipfa nyinshi",
    "symptoms_en": "Fever 41-42C, abundant nasal and eye discharge, mouth erosions, pneumonia, severe diarrhea",
    "cause": "Virus Morbillivirus - contagion rapide entre petits ruminants",
    "diagnosis": "Tableau clinique caracteristique. Test ELISA confirme. Declaration obligatoire",
    "treatment": "1. Pas de traitement specifique\n2. Antibiotiques contre surinfections\n3. Rehydratation orale\n4. Vitamines A et C\n5. Isolement strict",
    "treatment_en": "1. No specific treatment\n2. Antibiotics for superinfections\n3. Oral rehydration\n4. Vitamins",
    "prevention": "Vaccination annuelle OBLIGATOIRE. Controle des mouvements d'animaux",
    "vaccine": "Vaccin PPR - protection 3 ans - dose unique",
    "source": "FAO/CIRAD"
  },
  {
    "id": "ad-5",
    "animal": "Poule",
    "animal_rn": "Inkoko",
    "animal_en": "Chicken",
    "name": "Maladie de Newcastle",
    "name_en": "Newcastle Disease",
    "severity": "critique",
    "is_zoonotic": false,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Newcastle_disease_chicken.jpg/320px-Newcastle_disease_chicken.jpg",
    "symptoms": "Rales, toux, signes nerveux (torticolis, paralysie), diarrhee verte, chute ponte, mort subite",
    "symptoms_rn": "Indirimbo, ibimenyetso by'ubwonko (gukata ijosi), isave y'umutuku, impfuzi zipfa",
    "symptoms_en": "Rattles, cough, nervous signs (torticollis, paralysis), green diarrhea, drop in egg production, sudden death",
    "cause": "Virus Paramyxovirus - tres contagieux, survie longue dans l'environnement",
    "diagnosis": "Symptomes nerveux + respiratoires. Test hemagglutination-inhibition confirme",
    "treatment": "1. Pas de traitement curatif\n2. Antibiotiques pour surinfections bacteriennes\n3. Vitamines E et C\n4. Isolement strict des malades\n5. Desinfection profonde",
    "treatment_en": "1. No curative treatment\n2. Antibiotics for bacterial superinfections\n3. Vitamins E and C",
    "prevention": "Vaccination reguliere OBLIGATOIRE (tous les 2-3 mois). Biosecurite stricte",
    "vaccine": "Vaccin Newcastle (La Sota ou Clone 30) - tous les 2-3 mois",
    "source": "FAO/OIE"
  },
  {
    "id": "ad-6",
    "animal": "Poule",
    "animal_rn": "Inkoko",
    "animal_en": "Chicken",
    "name": "Coccidiose Aviaire",
    "name_en": "Avian Coccidiosis",
    "severity": "grave",
    "is_zoonotic": false,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Coccidiosis_poultry.jpg/320px-Coccidiosis_poultry.jpg",
    "symptoms": "Diarrhee sanguinolente, plumes herissees, poussins groupes sous lampe, amaigrissement rapide, forte mortalite jeunes",
    "symptoms_en": "Bloody diarrhea, ruffled feathers, chicks huddled under lamp, rapid weight loss, high mortality in young",
    "cause": "Parasite Eimeria spp. dans l'intestin - favorise par humidite et surpopulation",
    "diagnosis": "Fientes sanglantes caracteristiques. Oocystes Eimeria au microscope",
    "treatment": "1. Amprolium dans eau de boisson\n2. Toltrazuril (Baycox) dose unique\n3. Vitamine K contre hemorragies\n4. Sulfamides en alternative",
    "treatment_en": "1. Amprolium in drinking water\n2. Toltrazuril single dose\n3. Vitamin K against hemorrhages",
    "prevention": "Litiere seche et propre. Eviter surpeuplement. Coccidiostatiques preventifs dans aliments",
    "vaccine": "Pas de vaccin standard - preventif dans aliment",
    "source": "FAO"
  },
  {
    "id": "ad-7",
    "animal": "Porc",
    "animal_rn": "Ingurube",
    "animal_en": "Pig",
    "name": "Peste Porcine Africaine",
    "name_en": "African Swine Fever",
    "severity": "critique",
    "is_zoonotic": false,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/ASF_pig.jpg/320px-ASF_pig.jpg",
    "symptoms": "Fievre 40-42C, peau rouge/violacee oreilles et abdomen, hemorragies, vomissements, diarrhee sanguine, mort quasi certaine",
    "symptoms_en": "Fever 40-42C, red/purple skin on ears and abdomen, hemorrhages, vomiting, bloody diarrhea, near certain death",
    "cause": "Virus ADN africain - pas de vaccin disponible au monde",
    "diagnosis": "Tableau hemorrhagique. Mortalite proche 100%. PCR confirme. DECLARATION OBLIGATOIRE URGENTE",
    "treatment": "1. AUCUN TRAITEMENT - AUCUN VACCIN\n2. Abattage sanitaire TOTAL immediat\n3. Nettoyage desinfection profonde\n4. Signalement immediat veterinaire et autorites\n5. Quarantaine zone infectee",
    "treatment_en": "1. NO TREATMENT - NO VACCINE\n2. Total immediate sanitary slaughter\n3. Deep cleaning and disinfection\n4. Immediate reporting to authorities",
    "prevention": "Biosecurite maximale. Interdire dechets alimentaires aux porcs. Quarantaine 40 jours. Controle mouvements",
    "vaccine": "AUCUN VACCIN DISPONIBLE - biosecurite seule protection",
    "source": "OIE 2023"
  },
  {
    "id": "ad-8",
    "animal": "Lapin",
    "animal_rn": "Ikimanyi",
    "animal_en": "Rabbit",
    "name": "Coccidiose du Lapin",
    "name_en": "Rabbit Coccidiosis",
    "severity": "grave",
    "is_zoonotic": false,
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/r/r1/Rabbit_coccidiosis.jpg/320px-Rabbit_coccidiosis.jpg",
    "symptoms": "Diarrhee, amaigrissement, abdomen gonfle (forme hepatique), mortalite elevee lapereaux",
    "symptoms_en": "Diarrhea, weight loss, swollen abdomen (hepatic form), high mortality in young rabbits",
    "cause": "Parasite Eimeria spp. - favorise par cages sales et humides",
    "diagnosis": "Autopsie: nodules blancs sur foie (forme hepatique). Oocystes au microscope",
    "treatment": "1. Toltrazuril 10 mg/kg\n2. Sulfamides dans eau\n3. Traitement 5 jours\n4. Nettoyage cages",
    "treatment_en": "1. Toltrazuril 10 mg/kg\n2. Sulfonamides in water\n3. 5-day treatment",
    "prevention": "Litiere seche. Nettoyage regulier. Eviter surpopulation",
    "vaccine": "Pas de vaccin",
    "source": "FAO"
  }
];
